```yaml
version: "3"

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports: 
        - "9200:9200"
        - "9300:9300"
    volumes: 
        - elastic-data:/data
    environment: 
        - discovery.type=single-node
        
volumes:
    elastic-data: 
```

